Update main_bibliotheque.yml

diff --git a/.github/workflows/main_bibliotheque.yml b/.github/workflows/main_bibliotheque.yml
--- a/.github/workflows/main_bibliotheque.yml
+++ b/.github/workflows/main_bibliotheque.yml
@@ -18,13 +18,20 @@ jobs:
         with:
           python-version: '3.12'
 
-      - name: Install Python3 virtualenv
-        run: sudo apt-get install -y python3-venv
+      - name: Verify Python and venv
+        run: |
+          python3 --version
+          python3 -m venv --help
 
       - name: Create and start virtual environment
         run: |
           python3 -m venv venv
-          source venv/bin/activate
+          if [ -f venv/bin/activate ]; then
+            source venv/bin/activate
+          else
+            echo "Failed to create virtual environment"
+            exit 1
+          fi
       
       - name: Install dependencies
         run: |
